config/routes.rb
PharmaNewApp::Application.routes.draw do

  resources :pharmacies

  resources :prescriptions

  resources :users

  root :to => "users#index"

  match 'confirm', :controller => "pharmacies", :action => "confirm"

end

app/models/pharmacy.rb
class Pharmacy < ActiveRecord::Base
  attr_accessible :address, :email, :distance, :name, :phone
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  attr_accessible :name, :photo

  has_attached_file :photo

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :address, :dob, :email, :name, :phone, :insurance

  has_attached_file :insurance
	
=begin
	  :styles=> {
	      :thumbnail  => '30x30',
	      :medium     => '200x200'
	    }
=end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  # GET /pharmacies
  # GET /pharmacies.json
  def index
    @pharmacies = Pharmacy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pharmacies }
    end
  end

  # GET /pharmacies/1
  # GET /pharmacies/1.json
  def show
    @pharmacy = Pharmacy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pharmacy }
    end
  end

  # GET /pharmacies/new
  # GET /pharmacies/new.json
  def new
    @pharmacy = Pharmacy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pharmacy }
    end
  end

  # GET /pharmacies/1/edit
  def edit
    @pharmacy = Pharmacy.find(params[:id])
  end

  # POST /pharmacies
  # POST /pharmacies.json
  def create
    @pharmacy = Pharmacy.new(params[:pharmacy])

    respond_to do |format|
      if @pharmacy.save
        format.html { redirect_to @pharmacy, notice: 'Pharmacy was successfully created.' }
        format.json { render json: @pharmacy, status: :created, location: @pharmacy }
      else
        format.html { render action: "new" }
        format.json { render json: @pharmacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pharmacies/1
  # PUT /pharmacies/1.json
  def update
    @pharmacy = Pharmacy.find(params[:id])

    respond_to do |format|
      if @pharmacy.update_attributes(params[:pharmacy])
        format.html { redirect_to @pharmacy, notice: 'Pharmacy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pharmacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pharmacies/1
  # DELETE /pharmacies/1.json
  def destroy
    @pharmacy = Pharmacy.find(params[:id])
    @pharmacy.destroy

    respond_to do |format|
      format.html { redirect_to pharmacies_url }
      format.json { head :no_content }
    end
  end

  def confirm
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  # GET /prescriptions
  # GET /prescriptions.json
  def index
    @prescriptions = Prescription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prescriptions }
    end
  end


  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
    @prescription = Prescription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prescription }
    end
  end

  # GET /prescriptions/new
  # GET /prescriptions/new.json
  def new
    @prescription = Prescription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prescription }
    end
  end

  # GET /prescriptions/1/edit
  def edit
    @prescription = Prescription.find(params[:id])
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(params[:prescription])

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render json: @prescription, status: :created, location: @prescription }
      else
        format.html { render action: "new" }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prescriptions/1
  # PUT /prescriptions/1.json
  def update
    @prescription = Prescription.find(params[:id])

    respond_to do |format|
      if @prescription.update_attributes(params[:prescription])
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription = Prescription.find(params[:id])
    @prescription.destroy

    respond_to do |format|
      format.html { redirect_to prescriptions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper

	def change_date(time)
		time.to_date
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h3 Home

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
-# = link_to "PicScript", root_path, :class => 'brand'

= link_to image_tag("logo.png"), root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "PicScript"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner.nocolor
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/pharmacies/_form.html.haml
= form_for @pharmacy do |f|
  -if @pharmacy.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pharmacy.errors.count, "error")} prohibited this pharmacy from being saved:"
      %ul
        - @pharmacy.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :fax
    = f.text_field :fax
  .actions
    = f.submit 'Save'

app/views/pharmacies/confirm.html.haml
%h3 Confirmation email is on its way to confirm pickup time.
%br
%h3 Thanks for using PicScript!

app/views/pharmacies/edit.html.haml
%h1 Editing pharmacy

= render 'form'

= link_to 'Show', @pharmacy
\|
= link_to 'Back', pharmacies_path

app/views/pharmacies/index.html.haml
%h1 Pharmacies

%table.table
  %tr
    %th Name
    %th Address
    %th Email
    %th Phone
    %th Distance
    %th
    %th
    %th

  - @pharmacies.each do |pharmacy|
    %tr.nowhite
      %td
        = link_to pharmacy.name, pharmacy
      %td
        = link_to pharmacy.address, pharmacy
      %td
        = link_to pharmacy.email, pharmacy
      %td
        = link_to pharmacy.phone, pharmacy
      %td
        = link_to pharmacy.distance, pharmacy
    -#  
      %td= link_to 'Show', pharmacy
      %td= link_to 'Edit', edit_pharmacy_path(pharmacy)
      %td= link_to 'Destroy', pharmacy, :confirm => 'Are you sure?', :method => :delete

%br
.btn.btn-warning
  = link_to 'Enter Your Own Location'

app/views/pharmacies/new.html.haml
%h1 New pharmacy

= render 'form'

= link_to 'Back', pharmacies_path

app/views/pharmacies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @pharmacy.name
%p
  %b Address:
  = @pharmacy.address
%p
  %b Email:
  = @pharmacy.email
%p
  %b Phone:
  = @pharmacy.phone
%p
  %b Distance:
  = @pharmacy.distance

.btn.btn-warning
  = link_to 'Fill Prescription Now', confirm_path
\|
.btn.btn-warning
  = link_to 'Fill Prescription Later', pharmacies_path

app/views/prescriptions/_form.html.haml
= form_for @prescription do |f|
  -if @prescription.errors.any?
    #error_explanation
      %h2= "#{pluralize(@prescription.errors.count, "error")} prohibited this prescription from being saved:"
      %ul
        - @prescription.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :photo, 'Upload Script'
    = f.file_field :photo
  .actions
    = f.submit 'Save'

app/views/prescriptions/edit.html.haml
%h1 Editing prescription

= render 'form'

= link_to 'Show', @prescription
\|
= link_to 'Back', prescriptions_path

app/views/prescriptions/index.html.haml
%h1 My Prescriptions


- @prescriptions.each do |prescription|
  %table
    %tr
      %th= "Script Name: #{prescription.name}"
      %th
      %th
      %th
      %tr
        %td= image_tag prescription.photo
        %td.spacer
        %td.btn.btn-warning
          = link_to 'Edit', edit_prescription_path(prescription)
        %td.spacer
        %td.btn.btn-warning
          = link_to 'Delete', prescription, :confirm => 'Are you sure?', :method => :delete
        %td.spacer
        %td.btn.btn-success
          = link_to 'Find Closest Pharmacy', pharmacies_path

%br

.btn.btn-warning
  = link_to 'Add Prescription', new_prescription_path

app/views/prescriptions/new.html.haml
%h1 New prescription

= render 'form'

.btn.btn-warning
  = link_to 'Back', prescriptions_path

app/views/prescriptions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @prescription.name
%p
  %b Script:
  = image_tag @prescription.photo

.btn.btn-warning
  = link_to 'Change Photo', edit_prescription_path(@prescription)
\|
.btn.btn-warning
  = link_to 'Next', prescriptions_path

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :dob, 'Date of Birth (ex: 10/12/1983)'
    = f.text_field :dob
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.text_field :phone
  .filed
    = f.label :insurance
    = f.file_field :insurance
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Prescription Program Signup

-# Down to line 25 is commented out
  %table
    %tr
      %th Name
      %th Dob
      %th Address
      %th Email
      %th Phone
      %th
      %th
      %th

    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.dob
        %td= user.address
        %td= user.email
        %td= user.phone
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete 

%br

.btn.btn-warning
  = link_to 'Program Signup', new_user_path

- @users.each do |user|
  -# .btn.btn-warning
  -#   = link_to 'Show', user
  .btn.btn-warning
    = link_to 'Edit Signup Info', user
  .btn.btn-warning
    = link_to 'View Scripts', prescriptions_path
  .btn.btn-warning
    = link_to 'Fill New Script', new_prescription_path
  .btn.btn-danger
    = link_to 'Close Account', user, :confirm => 'Are you sure you want to close your account?', :method => :delete

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Date Of Birth:
  = @user.dob
%p
  %b Address:
  = @user.address
%p
  %b Email:
  = @user.email
%p
  %b Phone:
  = @user.phone

%p
  %b Image
  = image_tag( @user.insurance)

%p#map

.btn.btn-warning
  = link_to 'Edit', edit_user_path(@user)
\|
.btn.btn-warning
  = link_to 'Next', prescriptions_path